encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:article_name>", views.article, name="article"),
    path("search", views.search, name="search"),
    path("results", views.results, name="results"),
    path("newpage", views.new_page, name="newpage"),
    path("randompage", views.random_page, name="randompage"),
    path('wiki/<str:article_name>/edit/', views.edit_article, name='edit_article'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import markdown2
import random
import re
from . import util
from django import forms


class SearchInput(forms.Form):
    search_query = forms.CharField(label="Search:")


class NewPageInput(forms.Form):
    title = forms.CharField(label="Title:")
    body = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 40, 'width':"100%",}))

searchInput = SearchInput()

def index(request):
    
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": searchInput,
    })


def search(request):
    if request.method == "GET":
        searchInput = SearchInput(request.GET)
        if searchInput.is_valid():
            search_query = searchInput.cleaned_data["search_query"]

            # check if search query matches an existing entry. if yes redirect to that page
            if util.get_entry(search_query):
                return HttpResponseRedirect(f"/wiki/{search_query}")

            # if entry cannot be found, list entries that match as a substring and redirect to search results page
            else:
                all_entries = util.list_entries()

                # list all matched entries
                matched_entries = []
                for entry in all_entries:
                    if search_query in entry.lower():
                        matched_entries.append(entry)
                return render(request, "encyclopedia/results.html", {
                    "form": searchInput,
                    "matched_entries": matched_entries,
                    "search_query": search_query
                })

    return HttpResponseRedirect(reverse("wiki:index"))


def results(request):
    return render(request, "encyclopedia/results.html", {

    })


def article(request, article_name):
    article = util.get_entry(article_name)
    if article:
        print("article:", article)
        
        print("article title:", article_name)
        return render(request, "encyclopedia/article.html",
                      {"article": markdown2.markdown(article),
                       "article_title": article_name,
                        "form": searchInput,
                       })
    else:
        return HttpResponse("404 not found")


def new_page(request):
    newPageInput = NewPageInput()
    
    if request.method == "POST":
        form = NewPageInput(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            body = form.cleaned_data["body"]

            if (util.get_entry(title)):
                error = "Article already exists, try a different title."
                return render(request, "encyclopedia/newpage.html",
                    {
                        "form": searchInput,
                        "new_page_input": newPageInput,
                        "error": error,
                    })
            util.save_entry(title, body)
            return HttpResponseRedirect(f"/wiki/{title}")
            
    else:
        return render(request, "encyclopedia/newpage.html",
                    {
                        "form": searchInput,
                        "new_page_input": newPageInput
                    })


def edit_article(request, article_name):
    
    if request.method == "POST":
        form = NewPageInput(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            body = form.cleaned_data["body"]
            util.save_entry(title, body)
            return HttpResponseRedirect(f"/wiki/{title}")

    
    else:
        article = util.get_entry(article_name)
        if article:
            edit_data = {'title': article_name, 'body': article}
            edit_form = NewPageInput(initial=edit_data)
            return render(request, 'encyclopedia/edit_page.html', {
                "form": searchInput,
                'edit_form': edit_form,
                'article_title': article_name,
            })
        
def random_page(request):
    all_entries = util.list_entries()
    random_entry_name = random.choice(all_entries)
    random_entry = util.get_entry(random_entry_name)
    return render(request, "encyclopedia/article.html",
                  {"article": markdown2.markdown(random_entry),
                   "article_title": random_entry_name,
                    "form": searchInput,
                   })

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{article_title}}
{% endblock %}

{% block body %}
{{article | safe}}

<a href="{% url 'wiki:edit_article' article_name=article_title %}">Edit</a>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page
{% endblock %}

{% block body %}
    <h1>Edit page</h1>
    <form method="POST">
        {% csrf_token %}
        {{edit_form.as_p}}
        <button type="submit">Submit</button>
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="search" method="GET">
                    {{form}}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randompage' %}">Random page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a new page
{% endblock %}

{% block body %}
    <h1>Create a new page</h1>
    <form action="search" method="POST">
        {% csrf_token %}
        {{new_page_input}}
        <button type="submit">Submit</button>
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search results
{% endblock %}

{% block body %}
    <h1>Search results</h1>

    <p>
        There is no entry for <strong>"{{search_query}}"</strong> yet. Here are some matching entries:
    </p>
    <ul>
        {% for entry in matched_entries %}
            <li><a href="/wiki/{{ entry }}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}